### ISSUE TITLE
Example failes with Inacce

### ISSUE THREAD

**Issue by macbl** [rmannibucau/persistence-with-openejb-and-arquillian#1]
Running this example causes InaccessibleObjectException. Any ideas why?
(After several days of research I still didn't find any working example for TomEE + Arquillian * JPA )

Example result:

--------< org.superbiz:persistence-with-openejb-and-arquillian >--------
Building persistence-with-openejb-and-arquillian 1.0-SNAPSHOT
--------------------------------[ jar ]---------------------------------

--- maven-resources-plugin:2.4.3:resources (default-resources) @ persistence-with-openejb-and-arquillian ---
Using 'UTF-8' encoding to copy filtered resources.
Copying 1 resource

--- maven-compiler-plugin:2.3.2:compile (default-compile) @ persistence-with-openejb-and-arquillian ---
Nothing to compile - all classes are up to date

--- maven-resources-plugin:2.4.3:testResources (default-testResources) @ persistence-with-openejb-and-arquillian ---
Using 'UTF-8' encoding to copy filtered resources.
Copying 8 resources

--- maven-compiler-plugin:2.3.2:testCompile (default-testCompile) @ persistence-with-openejb-and-arquillian ---
Nothing to compile - all classes are up to date

--- maven-surefire-plugin:2.12.4:test (default-test) @ persistence-with-openejb-and-arquillian ---
Surefire report directory: C:\Users\Marcus\Documents\Temp\persistence-with-openejb-and-arquillian-master\target\surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.superbiz.PersonTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.104 sec <<< FAILURE!
org.superbiz.PersonTest  Time elapsed: 0.103 sec  <<< ERROR!
java.lang.RuntimeException: Could not create new instance of class org.jboss.arquillian.test.impl.EventTestRunnerAdaptor
	at org.jboss.arquillian.test.spi.SecurityActions.newInstance(SecurityActions.java:160)
	at org.jboss.arquillian.test.spi.SecurityActions.newInstance(SecurityActions.java:111)
	at org.jboss.arquillian.test.spi.SecurityActions.newInstance(SecurityActions.java:97)
	at org.jboss.arquillian.test.spi.TestRunnerAdaptorBuilder.build(TestRunnerAdaptorBuilder.java:52)
	at org.jboss.arquillian.junit.Arquillian.run(Arquillian.java:95)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.jboss.arquillian.test.spi.SecurityActions.newInstance(SecurityActions.java:156)
	... 16 more
Caused by: java.lang.RuntimeException: Could not create new instance of class org.jboss.arquillian.core.impl.ManagerImpl
	at org.jboss.arquillian.core.spi.SecurityActions.newInstance(SecurityActions.java:160)
	at org.jboss.arquillian.core.spi.SecurityActions.newInstance(SecurityActions.java:111)
	at org.jboss.arquillian.core.spi.SecurityActions.newInstance(SecurityActions.java:97)
	at org.jboss.arquillian.core.spi.ManagerBuilder.create(ManagerBuilder.java:77)
	at org.jboss.arquillian.test.impl.EventTestRunnerAdaptor.<init>(EventTestRunnerAdaptor.java:55)
	... 22 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.jboss.arquillian.core.spi.SecurityActions.newInstance(SecurityActions.java:156)
	... 26 more
Caused by: java.lang.ExceptionInInitializerError
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.jboss.arquillian.core.impl.loadable.SecurityActions.newInstance(SecurityActions.java:156)
	at org.jboss.arquillian.core.impl.loadable.JavaSPIExtensionLoader.createInstance(JavaSPIExtensionLoader.java:183)
	at org.jboss.arquillian.core.impl.loadable.JavaSPIExtensionLoader.createInstances(JavaSPIExtensionLoader.java:162)
	at org.jboss.arquillian.core.impl.loadable.JavaSPIExtensionLoader.all(JavaSPIExtensionLoader.java:65)
	at org.jboss.arquillian.core.impl.loadable.JavaSPIExtensionLoader.load(JavaSPIExtensionLoader.java:53)
	at org.jboss.arquillian.core.impl.loadable.LoadableExtensionLoader.load(LoadableExtensionLoader.java:73)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
	at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:99)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:81)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:145)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:116)
	at org.jboss.arquillian.core.impl.ManagerImpl.fireProcessing(ManagerImpl.java:346)
	at org.jboss.arquillian.core.impl.ManagerImpl.<init>(ManagerImpl.java:100)
	... 32 more
Caused by: java.lang.IllegalArgumentException: java.lang.reflect.InaccessibleObjectException: Unable to make field private volatile java.io.Writer java.util.logging.StreamHandler.writer accessible: module java.logging does not "opens java.util.logging" to unnamed module @2aafb23c
	at org.apache.openejb.util.reflection.Reflections.set(Reflections.java:78)
	at org.apache.openejb.util.JuliLogStreamFactory$OpenEJBSimpleLayoutHandler.<init>(JuliLogStreamFactory.java:202)
	at org.apache.openejb.arquillian.openejb.OpenEJBExtension.initLogger(OpenEJBExtension.java:60)
	at org.apache.openejb.arquillian.openejb.OpenEJBExtension.<clinit>(OpenEJBExtension.java:44)
	... 54 more
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field private volatile java.io.Writer java.util.logging.StreamHandler.writer accessible: module java.logging does not "opens java.util.logging" to unnamed module @2aafb23c
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
	at org.apache.openejb.util.reflection.Reflections.set(Reflections.java:68)
	... 57 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.jboss.arquillian.test.spi.SecurityActions.newInstance(SecurityActions.java:156)
	... 16 more
Caused by: java.lang.RuntimeException: Could not create new instance of class org.jboss.arquillian.core.impl.ManagerImpl
	at org.jboss.arquillian.core.spi.SecurityActions.newInstance(SecurityActions.java:160)
	at org.jboss.arquillian.core.spi.SecurityActions.newInstance(SecurityActions.java:111)
	at org.jboss.arquillian.core.spi.SecurityActions.newInstance(SecurityActions.java:97)
	at org.jboss.arquillian.core.spi.ManagerBuilder.create(ManagerBuilder.java:77)
	at org.jboss.arquillian.test.impl.EventTestRunnerAdaptor.<init>(EventTestRunnerAdaptor.java:55)
	... 22 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.jboss.arquillian.core.spi.SecurityActions.newInstance(SecurityActions.java:156)
	... 26 more
Caused by: java.lang.ExceptionInInitializerError
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.jboss.arquillian.core.impl.loadable.SecurityActions.newInstance(SecurityActions.java:156)
	at org.jboss.arquillian.core.impl.loadable.JavaSPIExtensionLoader.createInstance(JavaSPIExtensionLoader.java:183)
	at org.jboss.arquillian.core.impl.loadable.JavaSPIExtensionLoader.createInstances(JavaSPIExtensionLoader.java:162)
	at org.jboss.arquillian.core.impl.loadable.JavaSPIExtensionLoader.all(JavaSPIExtensionLoader.java:65)
	at org.jboss.arquillian.core.impl.loadable.JavaSPIExtensionLoader.load(JavaSPIExtensionLoader.java:53)
	at org.jboss.arquillian.core.impl.loadable.LoadableExtensionLoader.load(LoadableExtensionLoader.java:73)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
	at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:99)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:81)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:145)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:116)
	at org.jboss.arquillian.core.impl.ManagerImpl.fireProcessing(ManagerImpl.java:346)
	at org.jboss.arquillian.core.impl.ManagerImpl.<init>(ManagerImpl.java:100)
	... 32 more
Caused by: java.lang.IllegalArgumentException: java.lang.reflect.InaccessibleObjectException: Unable to make field private volatile java.io.Writer java.util.logging.StreamHandler.writer accessible: module java.logging does not "opens java.util.logging" to unnamed module @2aafb23c
	at org.apache.openejb.util.reflection.Reflections.set(Reflections.java:78)
	at org.apache.openejb.util.JuliLogStreamFactory$OpenEJBSimpleLayoutHandler.<init>(JuliLogStreamFactory.java:202)
	at org.apache.openejb.arquillian.openejb.OpenEJBExtension.initLogger(OpenEJBExtension.java:60)
	at org.apache.openejb.arquillian.openejb.OpenEJBExtension.<clinit>(OpenEJBExtension.java:44)
	... 54 more
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field private volatile java.io.Writer java.util.logging.StreamHandler.writer accessible: module java.logging does not "opens java.util.logging" to unnamed module @2aafb23c
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
	at org.apache.openejb.util.reflection.Reflections.set(Reflections.java:68)
	... 57 more

Results :

Tests in error: 
  org.superbiz.PersonTest: Could not create new instance of class org.jboss.arquillian.test.impl.EventTestRunnerAdaptor

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0

------------------------------------------------------------------------
BUILD FAILURE
------------------------------------------------------------------------
Total time:  3.319 s
Finished at: 2021-11-14T13:18:09+01:00
------------------------------------------------------------------------
Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project persistence-with-openejb-and-arquillian: There are test failures.

Please refer to C:\Users\Marcus\Documents\Temp\persistence-with-openejb-and-arquillian-master\target\surefire-reports for the individual test results.
-> [Help 1]

To see the full stack trace of the errors, re-run Maven with the -e switch.
Re-run Maven using the -X switch to enable full debug logging.

For more information about the errors and possible solutions, please read the following articles:
[Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by rmannibucau** [comment]
@macbl didn't look in details but looks like you use a too recent java version or a too old openejb (stack) version. Ensuring both are consistent would likely solve it.
